version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  lint_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
workflows:
  version: 2
  validate:
    jobs:
      - lint_and_test
