version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm test
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm lint
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test